### ISSUE TITLE
Bug about shoot range

### ISSUE THREAD

**Issue by runxinghuan** [AY2324S2-CS2113-F15-3/tp#174]
![image](https://github.com/AY2324S2-CS2113-F15-3/tp/assets/110675437/be993885-d475-4b7a-9925-fc84e4c021ca)
When I enter shoot 0, sometimes the direction generated is negative. This cannot pass the assertion.

**Comment by HenryGan138** [comment]
Yes, I understand your concern. I am thinking about if it is possible not showing those parameter, also concerning #137.
