### ISSUE TITLE
Suggestion about shoot range

### ISSUE THREAD

**Issue by runxinghuan** [AY2324S2-CS2113-F15-3/tp#175]
![image](https://github.com/AY2324S2-CS2113-F15-3/tp/assets/110675437/aba59a31-457b-48f8-ab80-5b9d50f7a9ee)
I think need to edit the range, because now it is really difficult to save 1 goal and miss one goal. This causes me not able to end the game early.

**Comment by HenryGan138** [comment]
It seems you are in the EASY difficulty. The game supposed to get harder if player change the difficulty.
